export const locales = ['en', 'nl', 'de', 'fr'] as const;
export type Locale = (typeof locales)[number];

const en = {
  language: 'Language', eyebrow: 'Packaged food, made clearer', titleStart: 'Know what is', titleAccent: 'inside.',
  intro: 'Search trusted product data across Europe. Nutrition details are available with Foodscope Plus.',
  searchLabel: 'Search products', searchPlaceholder: 'Try “oat milk” or “dark chocolate”', search: 'Search', searching: 'Searching…',
  recent: 'Recent searches', clear: 'Clear results', results: 'Search results', resultCount: 'products shown',
  emptyStart: 'Start with a product you are curious about.', emptyResults: 'No matching products found. Try another term.',
  error: 'We could not complete that search. Please try again.', unavailable: 'Unavailable', unknownBrand: 'Brand unavailable',
  nutrition: 'Nutrition per 100 g', energyKcal: 'Energy', fat: 'Fat', saturatedFat: 'Saturated fat', carbohydrates: 'Carbohydrates', sugars: 'Sugars', protein: 'Protein', salt: 'Salt', sodium: 'Sodium',
  locked: 'Nutrition is locked', lockedBody: 'Upgrade to view detailed nutrition for every product.',
  plan: 'Foodscope Plus', active: 'Nutrition unlocked', inactive: 'Free plan', subscribe: 'Unlock nutrition', redirecting: 'Opening Checkout…', accountUnavailable: 'Plan status unavailable', retryAccount: 'Retry plan status',
  subscriptionBody: 'Detailed nutrition for smarter choices.', monthly: 'Monthly subscription · Stripe test mode', loading: 'Loading your Foodscope…',
};

export type Messages = typeof en;
export const dictionaries: Record<Locale, Messages> = {
  en,
  nl: {
    language: 'Taal', eyebrow: 'Verpakte voeding, duidelijker gemaakt', titleStart: 'Weet wat erin', titleAccent: 'zit.', intro: 'Zoek betrouwbare productgegevens in Europa. Voedingsdetails zijn beschikbaar met Foodscope Plus.', searchLabel: 'Producten zoeken', searchPlaceholder: 'Probeer “havermelk” of “pure chocolade”', search: 'Zoeken', searching: 'Zoeken…', recent: 'Recente zoekopdrachten', clear: 'Resultaten wissen', results: 'Zoekresultaten', resultCount: 'producten weergegeven', emptyStart: 'Begin met een product waar je nieuwsgierig naar bent.', emptyResults: 'Geen passende producten gevonden. Probeer een andere term.', error: 'We konden die zoekopdracht niet voltooien. Probeer het opnieuw.', unavailable: 'Niet beschikbaar', unknownBrand: 'Merk niet beschikbaar', nutrition: 'Voeding per 100 g', energyKcal: 'Energie', fat: 'Vet', saturatedFat: 'Verzadigd vet', carbohydrates: 'Koolhydraten', sugars: 'Suikers', protein: 'Eiwitten', salt: 'Zout', sodium: 'Natrium', locked: 'Voedingswaarden zijn vergrendeld', lockedBody: 'Upgrade om gedetailleerde voedingswaarden van elk product te bekijken.', plan: 'Foodscope Plus', active: 'Voedingswaarden ontgrendeld', inactive: 'Gratis abonnement', subscribe: 'Voedingswaarden ontgrendelen', redirecting: 'Checkout openen…', accountUnavailable: 'Abonnementsstatus niet beschikbaar', retryAccount: 'Status opnieuw laden', subscriptionBody: 'Gedetailleerde voedingswaarden voor slimmere keuzes.', monthly: 'Maandelijks abonnement · Stripe-testmodus', loading: 'Foodscope laden…',
  },
  de: {
    language: 'Sprache', eyebrow: 'Verpackte Lebensmittel, verständlich gemacht', titleStart: 'Wissen, was', titleAccent: 'drin ist.', intro: 'Durchsuche verlässliche Produktdaten aus Europa. Nährwertdetails gibt es mit Foodscope Plus.', searchLabel: 'Produkte suchen', searchPlaceholder: 'Versuche „Hafermilch“ oder „dunkle Schokolade“', search: 'Suchen', searching: 'Suche…', recent: 'Letzte Suchanfragen', clear: 'Ergebnisse löschen', results: 'Suchergebnisse', resultCount: 'Produkte angezeigt', emptyStart: 'Beginne mit einem Produkt, das dich interessiert.', emptyResults: 'Keine passenden Produkte gefunden. Versuche einen anderen Begriff.', error: 'Die Suche konnte nicht abgeschlossen werden. Bitte erneut versuchen.', unavailable: 'Nicht verfügbar', unknownBrand: 'Marke nicht verfügbar', nutrition: 'Nährwerte pro 100 g', energyKcal: 'Energie', fat: 'Fett', saturatedFat: 'Gesättigte Fettsäuren', carbohydrates: 'Kohlenhydrate', sugars: 'Zucker', protein: 'Eiweiß', salt: 'Salz', sodium: 'Natrium', locked: 'Nährwerte sind gesperrt', lockedBody: 'Mit einem Upgrade siehst du detaillierte Nährwerte für jedes Produkt.', plan: 'Foodscope Plus', active: 'Nährwerte freigeschaltet', inactive: 'Kostenloser Tarif', subscribe: 'Nährwerte freischalten', redirecting: 'Checkout wird geöffnet…', accountUnavailable: 'Tarifstatus nicht verfügbar', retryAccount: 'Tarifstatus erneut laden', subscriptionBody: 'Detaillierte Nährwerte für klügere Entscheidungen.', monthly: 'Monatsabonnement · Stripe-Testmodus', loading: 'Foodscope wird geladen…',
  },
  fr: {
    language: 'Langue', eyebrow: 'Les aliments emballés, en toute clarté', titleStart: 'Savoir ce qu’il y a', titleAccent: 'dedans.', intro: 'Recherchez des données fiables sur les produits européens. Les détails nutritionnels sont disponibles avec Foodscope Plus.', searchLabel: 'Rechercher des produits', searchPlaceholder: 'Essayez « lait d’avoine » ou « chocolat noir »', search: 'Rechercher', searching: 'Recherche…', recent: 'Recherches récentes', clear: 'Effacer les résultats', results: 'Résultats', resultCount: 'produits affichés', emptyStart: 'Commencez par un produit qui vous intrigue.', emptyResults: 'Aucun produit correspondant. Essayez un autre terme.', error: 'Nous n’avons pas pu effectuer cette recherche. Réessayez.', unavailable: 'Indisponible', unknownBrand: 'Marque indisponible', nutrition: 'Nutrition pour 100 g', energyKcal: 'Énergie', fat: 'Matières grasses', saturatedFat: 'Graisses saturées', carbohydrates: 'Glucides', sugars: 'Sucres', protein: 'Protéines', salt: 'Sel', sodium: 'Sodium', locked: 'La nutrition est verrouillée', lockedBody: 'Passez à la formule supérieure pour voir les valeurs nutritionnelles détaillées.', plan: 'Foodscope Plus', active: 'Nutrition déverrouillée', inactive: 'Formule gratuite', subscribe: 'Déverrouiller la nutrition', redirecting: 'Ouverture du paiement…', accountUnavailable: 'Statut de l’abonnement indisponible', retryAccount: 'Réessayer le statut', subscriptionBody: 'Des valeurs nutritionnelles détaillées pour mieux choisir.', monthly: 'Abonnement mensuel · Mode test Stripe', loading: 'Chargement de Foodscope…',
  },
};
