export const locales = ['en', 'nl', 'de', 'fr'] as const;
export type Locale = (typeof locales)[number];

const en = {
  language: 'Language', eyebrow: 'Packaged food, made clearer', titleStart: 'Know what is', titleAccent: 'inside.',
  intro: 'Search community-contributed packaged-food data. Product details may be incomplete or incorrect. Available nutrition details are included with Foodscope Plus.',
  searchLabel: 'Search products', searchPlaceholder: 'Try “oat milk” or “dark chocolate”', search: 'Search', searching: 'Searching…',
  recent: 'Recent searches', clear: 'Clear results', results: 'Search results', resultCount: 'products shown',
  emptyStart: 'Start with a product you are curious about.', emptyResults: 'No matching products found. Try another term.',
  error: 'We could not complete that search. Please try again.', unavailable: 'Unavailable', unknownBrand: 'Brand unavailable',
  nutrition: 'Nutrition per 100 g', energyKcal: 'Energy', fat: 'Fat', saturatedFat: 'Saturated fat', carbohydrates: 'Carbohydrates', sugars: 'Sugars', protein: 'Protein', salt: 'Salt', sodium: 'Sodium',
  locked: 'Nutrition is locked', lockedBody: 'Upgrade to view available nutrition details.',
  plan: 'Foodscope Plus', active: 'Nutrition unlocked', inactive: 'Free plan', subscribe: 'Unlock nutrition', redirecting: 'Opening Checkout…', checkoutCancelled: 'Checkout was canceled. Your plan was not changed.', accountUnavailable: 'Plan status unavailable', retryAccount: 'Retry plan status',
  checkoutError: 'We could not open Checkout. Please try again.',
  subscriptionBody: 'Detailed nutrition for smarter choices.', monthly: 'Monthly subscription · Stripe test mode', loading: 'Loading your Foodscope…',
  attributionPrefix: 'Contains information from', attributionLicense: 'available under the', imageAttribution: 'Product images are available under',
};

export type Messages = typeof en;
export const dictionaries: Record<Locale, Messages> = {
  en,
  nl: {
    language: 'Taal', eyebrow: 'Verpakte voeding, duidelijker gemaakt', titleStart: 'Weet wat erin', titleAccent: 'zit.', intro: 'Doorzoek productgegevens die door de gemeenschap zijn aangeleverd. Gegevens kunnen onvolledig of onjuist zijn. Beschikbare voedingsdetails zijn inbegrepen bij Foodscope Plus.', searchLabel: 'Producten zoeken', searchPlaceholder: 'Probeer “havermelk” of “pure chocolade”', search: 'Zoeken', searching: 'Zoeken…', recent: 'Recente zoekopdrachten', clear: 'Resultaten wissen', results: 'Zoekresultaten', resultCount: 'producten weergegeven', emptyStart: 'Begin met een product waar je nieuwsgierig naar bent.', emptyResults: 'Geen passende producten gevonden. Probeer een andere term.', error: 'We konden die zoekopdracht niet voltooien. Probeer het opnieuw.', unavailable: 'Niet beschikbaar', unknownBrand: 'Merk niet beschikbaar', nutrition: 'Voeding per 100 g', energyKcal: 'Energie', fat: 'Vet', saturatedFat: 'Verzadigd vet', carbohydrates: 'Koolhydraten', sugars: 'Suikers', protein: 'Eiwitten', salt: 'Zout', sodium: 'Natrium', locked: 'Voedingswaarden zijn vergrendeld', lockedBody: 'Upgrade om beschikbare voedingswaarden te bekijken.', plan: 'Foodscope Plus', active: 'Voedingswaarden ontgrendeld', inactive: 'Gratis abonnement', subscribe: 'Voedingswaarden ontgrendelen', redirecting: 'Checkout openen…', checkoutCancelled: 'Checkout is geannuleerd. Je abonnement is niet gewijzigd.', accountUnavailable: 'Abonnementsstatus niet beschikbaar', retryAccount: 'Status opnieuw laden', checkoutError: 'We konden Checkout niet openen. Probeer het opnieuw.', subscriptionBody: 'Gedetailleerde voedingswaarden voor slimmere keuzes.', monthly: 'Maandelijks abonnement · Stripe-testmodus', loading: 'Foodscope laden…', attributionPrefix: 'Bevat informatie van', attributionLicense: 'beschikbaar onder de', imageAttribution: 'Productafbeeldingen zijn beschikbaar onder',
  },
  de: {
    language: 'Sprache', eyebrow: 'Verpackte Lebensmittel, verständlich gemacht', titleStart: 'Wissen, was', titleAccent: 'drin ist.', intro: 'Durchsuche von der Community bereitgestellte Produktdaten. Angaben können unvollständig oder falsch sein. Verfügbare Nährwertdetails sind in Foodscope Plus enthalten.', searchLabel: 'Produkte suchen', searchPlaceholder: 'Versuche „Hafermilch“ oder „dunkle Schokolade“', search: 'Suchen', searching: 'Suche…', recent: 'Letzte Suchanfragen', clear: 'Ergebnisse löschen', results: 'Suchergebnisse', resultCount: 'Produkte angezeigt', emptyStart: 'Beginne mit einem Produkt, das dich interessiert.', emptyResults: 'Keine passenden Produkte gefunden. Versuche einen anderen Begriff.', error: 'Die Suche konnte nicht abgeschlossen werden. Bitte erneut versuchen.', unavailable: 'Nicht verfügbar', unknownBrand: 'Marke nicht verfügbar', nutrition: 'Nährwerte pro 100 g', energyKcal: 'Energie', fat: 'Fett', saturatedFat: 'Gesättigte Fettsäuren', carbohydrates: 'Kohlenhydrate', sugars: 'Zucker', protein: 'Eiweiß', salt: 'Salz', sodium: 'Natrium', locked: 'Nährwerte sind gesperrt', lockedBody: 'Mit einem Upgrade siehst du verfügbare Nährwertdetails.', plan: 'Foodscope Plus', active: 'Nährwerte freigeschaltet', inactive: 'Kostenloser Tarif', subscribe: 'Nährwerte freischalten', redirecting: 'Checkout wird geöffnet…', checkoutCancelled: 'Checkout wurde abgebrochen. Dein Tarif wurde nicht geändert.', accountUnavailable: 'Tarifstatus nicht verfügbar', retryAccount: 'Tarifstatus erneut laden', checkoutError: 'Checkout konnte nicht geöffnet werden. Bitte versuche es erneut.', subscriptionBody: 'Detaillierte Nährwerte für klügere Entscheidungen.', monthly: 'Monatsabonnement · Stripe-Testmodus', loading: 'Foodscope wird geladen…', attributionPrefix: 'Enthält Informationen von', attributionLicense: 'verfügbar unter der', imageAttribution: 'Produktbilder sind verfügbar unter',
  },
  fr: {
    language: 'Langue', eyebrow: 'Les aliments emballés, en toute clarté', titleStart: 'Savoir ce qu’il y a', titleAccent: 'dedans.', intro: 'Recherchez des données sur les produits fournies par la communauté. Ces données peuvent être incomplètes ou erronées. Les informations nutritionnelles disponibles sont incluses avec Foodscope Plus.', searchLabel: 'Rechercher des produits', searchPlaceholder: 'Essayez « lait d’avoine » ou « chocolat noir »', search: 'Rechercher', searching: 'Recherche…', recent: 'Recherches récentes', clear: 'Effacer les résultats', results: 'Résultats', resultCount: 'produits affichés', emptyStart: 'Commencez par un produit qui vous intrigue.', emptyResults: 'Aucun produit correspondant. Essayez un autre terme.', error: 'Nous n’avons pas pu effectuer cette recherche. Réessayez.', unavailable: 'Indisponible', unknownBrand: 'Marque indisponible', nutrition: 'Nutrition pour 100 g', energyKcal: 'Énergie', fat: 'Matières grasses', saturatedFat: 'Graisses saturées', carbohydrates: 'Glucides', sugars: 'Sucres', protein: 'Protéines', salt: 'Sel', sodium: 'Sodium', locked: 'La nutrition est verrouillée', lockedBody: 'Passez à la formule supérieure pour voir les informations nutritionnelles disponibles.', plan: 'Foodscope Plus', active: 'Nutrition déverrouillée', inactive: 'Formule gratuite', subscribe: 'Déverrouiller la nutrition', redirecting: 'Ouverture du paiement…', checkoutCancelled: 'Le paiement a été annulé. Votre formule n’a pas changé.', accountUnavailable: 'Statut de l’abonnement indisponible', retryAccount: 'Réessayer le statut', checkoutError: 'Impossible d’ouvrir Checkout. Réessayez.', subscriptionBody: 'Des valeurs nutritionnelles détaillées pour mieux choisir.', monthly: 'Abonnement mensuel · Mode test Stripe', loading: 'Chargement de Foodscope…', attributionPrefix: 'Contient des informations provenant de', attributionLicense: 'disponibles sous la', imageAttribution: 'Les images des produits sont disponibles sous',
  },
};
